### ISSUE TITLE
ValidateSourceAdvanced failed 

### ISSUE THREAD

**Issue by gn02960889** [thetatoken/guardian-mainnet-guide#78]
I found a lot of error message on log file. Is this normal?

[2021-03-11 18:10:38.112] [error] [2021-03-11 18:10:38] WARN [ledger] validateSourceAdvanced failed on 0xAE17b59b2587D01AFa10361b5045B14DB627B2E8: Result{code:100002, message:ValidateInputAdvanced: Got 4, expected 5. (acc.seq=4)}
[2021-03-11 18:10:38.112] [info] [2021-03-11 18:10:38] WARN [ledger] validateSourceAdvanced failed on 0xAE17b59b2587D01AFa10361b5045B14DB627B2E8: Result{code:100002, message:ValidateInputAdvanced: Got 4, expected 5. (acc.seq=4)}

**Comment by Larix-Laricina** [comment]
I also have lots of these, would be useful to know what they mean.

**Comment by nexster** [comment]
My power went out a few days ago and now I just get this messege in log and no Tfuel.  So much for passive income.

**Comment by OzymandiasOwl75** [comment]
I the same gaurdian node WARN about validateSourceAdvanced failed. I have only being running Gaurdian Node for 24 hours. Still no TFuel. Connectivity says good with 23 Gaurdian Peers. I assume lack of TFuel earned relates to this message

**Comment by nexster** [comment]
I unstaked and now I am waiting waiting 3 days for theta back.  Will wipe node computer and restake.  Will update results then.

**Comment by OzymandiasOwl75** [comment]
> I unstaked and now I am waiting waiting 3 days for theta back. Will wipe node computer and restake. Will update results then.

I am not certain its a problem with node setup. Noticed on my Edge Node I have pending earnings of 0.0015 TFuel. I am new to this, but its clear guardian node is showing TFuel rounded to a whole number. I am only staking 1000 Theta, which is minimum requirement. Maybe there is'nt an issue, but it would be interesting to know what TFuel earning should be expected on 1000 Theta staked over 24 hours

**Comment by nexster** [comment]
I have 1100 Theta and it was making 1.2 Tfuel a day.  But 0 per day for last 3 days since my power went 9out.

**Comment by OzymandiasOwl75** [comment]
> I have 1100 Theta and it was making 1.2 Tfuel a day. But 0 per day for last 3 days since my power went 9out.

OK, thanks for that. I will leave mine running and see it it resolves itself. I will let you know how I get on

**Comment by gn02960889** [comment]
@jieyilong I saw many "ValidateSourceAdvanced failed" message and no Tfuel rewards.Any ideas about this case?

**Comment by AquaWookie** [comment]
Same issue. After approximately 2 months of a functional node, 2 days ago I stopped receiving TFuel and now the logs are telling me the same shenanigans: 

[2021-03-12 07:23:49.109] [info] [2021-03-12 07:23:49]  WARN [ledger] validateSourceAdvanced failed on 0x147F2Dd6A52Be02ecBCc5488fbc6636AD28FA989: Result{code:100002, message:ValidateInputAdvanced: Got 5, expected 6. (acc.seq=5)}

![image](https://user-images.githubusercontent.com/37837732/110942085-4aed2f80-8307-11eb-9a3e-2ddc1af103bd.png)

Not having any luck troubleshooting...

**Comment by Waldojesus** [comment]
I'm actually having something strange happen as well. I think I'm receiving too much Tfuel. I had been averaging about one a day and last night I earned 12. I wonder if there is some weird redistribution happening from failed nodes.

**Comment by gn02960889** [comment]
@AquaWookie That is what I see. Health check failed

**Comment by sirbrokealot** [comment]
I have the same problem with  2.2.10.

Interesting for me ist visiting https://guardianmonitor.io/ and scroll way down and search for my Guardian Node address.
It actually shows an increasing 1DTf number while in the GN app there is a frozen 0 session earnings.

In the Log I get for example: [2021-03-13 12:07:04.018] [error] [2021-03-13 12:07:04]  WARN [ledger] validateSourceAdvanced failed on 0xb9bc591387b58a269ee94EB0602E54E78FfaFfb2: Result{code:100002, message:ValidateInputAdvanced: Got 125, expected 126. (acc.seq=125)}

The Stopping, Starting bug could maybe be resolved with clicking Node -> Deleting Node Database

Some people said, that the distribution from Tfuel has changed recently and we could check some "medium" article.

Please clarify where can we read about it and how to fix the 0 session earning which might be connected to the  validateSourceAdvanced failed error.

**Comment by OzymandiasOwl75** [comment]
> I have the same problem with 2.2.10.
> 
> Interesting for me ist visiting https://guardianmonitor.io/ and scroll way down and search for my Guardian Node address.
> It actually shows an increasing 1DTf number while in the GN app there is a frozen 0 session earnings.
> 
> In the log I get for example: [2021-03-13 12:07:04.018] [error] [2021-03-13 12:07:04] WARN [ledger] validateSourceAdvanced failed on 0xb9bc591387b58a269ee94EB0602E54E78FfaFfb2: Result{code:100002, message:ValidateInputAdvanced: Got 125, expected 126. (acc.seq=125)}
> 
> The stopping, starting bug could maybe be resolved with clicking Node -> Deleting Node Database
> 
> Some people said, that the distribution from Tfuel has changed recently and we could check some "medium" article.
> 
> Please clarify where can we read about it and how to fix the 0 session earning which might be connected to the validateSourceAdvanced failed error.

I have heard that Theta have changed the way TFuel is accrued. You still get the same amount of TFuel, but the payments to your account are accumulated. 

I have heard it relates to the Theta MainNet 3.0 upgrade. I suspect what you are seeing is the TFuel has been accrued. I assume a Gaurdian Node upgrade maybe available for this next month https://www.thetatoken.org/

**Comment by sirbrokealot** [comment]
Thanks is there anything to read about accumulation thresholds?

ATTENTION DONT FALL FOR SCAMS IN THIS MATTER.
I got some chat inquiries from the scammer thetatokens (https://www.reddit.com/user/thetatokens)
and his scam site  https://thetawebwalletsio.com 
BE ADVISED DONT FALL FOR THIS SCAM

**Comment by the-quantum-rabbit** [comment]
I'm getting the same issue after the node dropping 2 or 3 days ago. On restarting theta , the sync stopped at 
Thu Mar 11 07:49:21 CET 2021
{
    "address": "0x99d5AA6C86E690054f5B63DED992fB8E48ba6dAA",
    "chain_id": "mainnet",
    "current_epoch": "9585082",
    "current_height": "9508409",
    "current_time": "1615445361",
    "latest_finalized_block_epoch": "9574152",
    "latest_finalized_block_hash": "0xf8a92d717c75647142263913b6080feb7cdc34c1453a665cb89ccf9f2fe8fdea",
    "latest_finalized_block_height": "9497499",
    "latest_finalized_block_time": "1615370641",
    "peer_id": "0x99d5AA6C86E690054f5B63DED992fB8E48ba6dAA",
    "syncing": true
}

Converting finalised_block_time 1615370641 timestamp in seconds to readable date with
https://www.epochconverter.com/

Assuming that this timestamp is in seconds:
GMT: Wednesday 10 March 2021 10:04:01
Your time zone: mercredi 10 mars 2021 11:04:01 GMT+01:00
Relative: 21 hours ago

I first tried a restart but the sync stopped again, so deleted the db and snapshot, got a new snapshot and restarted.
sync again stops on another block. I see a lot of WARN [ledger] validateSourceAdvanced failed  messages with sequence errors as reported before.
I have tried differnt snapshots with the same results.
:-(

**Comment by OzymandiasOwl75** [comment]
> Thanks is there anything to read about accumulation thresholds?
> 
> ATTENTION DONT FALL FOR SCAMS IN THIS MATTER.
> I got some chat inquiries from the scammer thetatokens (https://www.reddit.com/user/thetatokens)
> and his scam site https://thetawebwalletsio.com
> BE ADVISED DONT FALL FOR THIS SCAM

I really am very new to all this, but its clear Theta MainNet is currently going through a period of change and expansion. That's what I like about it.

https://medium.com/theta-network/theta-protocol-code-v2-2-0-released-with-important-performance-related-updates-6b9e2261d0ae

The more I read the more I like it.

https://medium.com/theta-network/theta-network-2021-roadmap-69053f16a870

**Comment by rchandi** [comment]
Hi All,

I am having the same problem.

I started up my guardian node (on a desktop) about 1 day ago and currently I am showing 0.00 Session earnings on the Guardian node, however; on https://guardianmonitor.io/ my node is said to be online and it looks like it is accruing TFuel rewards.  

The logs are also showing:

WARN [ledger] validateSourceAdvanced failed on 0x2FeF30e4cAfddDC10b06FCC07459F54A559c1A3B: Result{code:100002, message:ValidateInputAdvanced: Got 6, expected 7. (acc.seq=6)}

I am going to let it run for a few days and maybe it works itself out.  If not I will have to try to un-install and re-install the entire node...not sure what else I can do.

**Comment by DavidGarry7654** [comment]
@rchandi Hello Mate, Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink https://t.me/thetatokensupports. They'll be happy to resolve your issue. Cheers.

**Comment by DavidGarry7654** [comment]
@rchandi Hello Mate, Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink https://t.me/thetatokensupports. They'll be happy to resolve your issue. Cheers.

**Comment by DavidGarry7654** [comment]
@rchandi Have you been able to reach out to ther telegram support ?

**Comment by nexster** [comment]
I have not.  Does not matter to me my theta is already unstaked waiting for it to return to wallet.  Install new guardians node and try that.

**Comment by DavidGarry7654** [comment]
Okay. Lucky you @rchandi Can contact Theta Network Support on Telegram via the weblink https://t.me/thetatokensupports. They'll be happy to resolve your issue.

**Comment by rchandi** [comment]
@DavidGarry7654 thanks for the tip.  I have reached out and will see what they recommend.

**Comment by DavidGarry7654** [comment]
@rchandi Hope you created a username for yourself on your telegram account before messaging them ?

**Comment by DavidGarry7654** [comment]
@rchandi Hope you created a username for yourself on your telegram account before messaging them ?

**Comment by nexster** [comment]
I deleted my guardian node,  reinstalled,  restaked still getting same errors in log,  but it looks like it’s working from UI.  No Tfuel yet.  Will update if I get any Tfuel,

**Comment by rchandi** [comment]
I emailed the Theta support team. Will keep everyone updated here.

**Comment by phyx1u5** [comment]
im also getting the same problem, syncing is flase, but keep getting these validaorSourceAdvanced failed errors, im using the Linux CLI version

**Comment by rrln** [comment]
> 
> 
> I found a lot of error message on log file. Is this normal?
> 
> [2021-03-11 18:10:38.112] [error] [2021-03-11 18:10:38] WARN [ledger] validateSourceAdvanced failed on 0xAE17b59b2587D01AFa10361b5045B14DB627B2E8: Result{code:100002, message:ValidateInputAdvanced: Got 4, expected 5. (acc.seq=4)}
> [2021-03-11 18:10:38.112] [info] [2021-03-11 18:10:38] WARN [ledger] validateSourceAdvanced failed on 0xAE17b59b2587D01AFa10361b5045B14DB627B2E8: Result{code:100002, message:ValidateInputAdvanced: Got 4, expected 5. (acc.seq=4)}

Following are my observations (I'm not an expert att all).
It looks like there are two diffrent log entries on each row in the original post above.
I.e first an entry "[2021-03-11 18:10:38.112] [error] " for one event.
Then an entry, on the same row but for another event "[2021-03-11 18:10:38] WARN [ledger] validateSourceAdvanced failed ... "

I do think that the problem is that there are two theta processes running after a restart.
I have several nodes and have seen this problem.
Solved on Windowd nodes by closing down the GN, kill all processes associated to GN still running (The Guardian Node, theta) via Task manager. Then start the GN (no need to clean DB/snapshoot. I had to reboot my linux servers at one point, this could be the reason for that as well, didn't check the processes before reboot.

I don't know for sure, but I do think "WARN [ledger] validateSourceAdvanced failed ... " is ok and per design of the protocol before consencus is reached. It is a warning, not an error.

**Comment by Ijacques** [comment]
Me to I am having several error codes showing on my node log, also my session earnings shows a constant zero yet I see that I am earning a lil tfuel because the total tfuel balance has increased a lil. I hope they work these bugs out soon.

**Comment by DavidGarry7654** [comment]
@Ijacques Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink https://t.me/thetanetworking. They'll be happy to resolve your issue. Cheers.

**Comment by DavidGarry7654** [comment]
@Ijacques Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink https://t.me/thetanetworking. They'll be happy to resolve your issue. Cheers.

**Comment by nexster** [comment]
Not getting error messages anymore now just getting WARN ledger messages.  No Tfuel yet.

**Comment by DavidGarry7654** [comment]
Have you messaged theta on telegram ?

**Comment by rchandi** [comment]
> I emailed the Theta support team. Will keep everyone updated here.

Hi Everyone,

I still have not heard back from the support team but I am starting to see TFuel earnings on my guardian node.

I suspect the log error:

"WARN [ledger] validateSourceAdvanced failed on 0x90a5C68EB3A4391fb48f9e7bd7B2d39Fb32601CD: Result{code:100002, message:ValidateInputAdvanced: Got 60, expected 61. (acc.seq=60)}"... Is unrelated to the tfuel sessions earning issue and may be a natural part of the guardian node and not a "bug".

**Comment by DavidGarry7654** [comment]
@rchandi Have you tried the theta support on telegram?

**Comment by Kuehn** [comment]
@DavidGarry7654 So I also am having the same error messages and experience @rchandi  appears to be having. I did go to telegram for the first time. Last message was on Feb 11th appeared to be stating it's on discord. Maybe I went to the wrong telegram group? Either way I asked my question there and everyone just stated to stake with Gpool to not have those issues anymore. So, I am going to keep looking into it. I'd rather not go stake with Gpool. Will post if I find a resolution to this error as well.

**Comment by DavidGarry7654** [comment]
Hello Kuehn. I think you went to the wrong telegram group. Here’s a link to the current telegram group https://t.me/thetanetworking. Let me know when you’ve gotten through

**Comment by DavidGarry7654** [comment]
@Kuehn Have you gotten through the correct telegram via https://t.me/thetanetworking. Let me know when you’ve gotten through

**Comment by DavidGarry7654** [comment]
@Kuehn Any luck ?

**Comment by Kuehn** [comment]
@DavidGarry7654 So I did reach out to theta support via telegram you sent, and they were going to help me out, however I went to my log and the error stopped showing up, had some warnings but the ValidateSourceAdvanced failed error was no longer there. So I am letting it run for a while and going to see if it comes back. Thanks for all your help so far.

**Comment by DavidGarry7654** [comment]
You’re welcome Kuehn. Did they tell you to backup your node to avoid the same error from coming back ?

**Comment by sirbrokealot** [comment]
If you got it fixed can you please tell us how you did it and what was suggested by theta support.

I still have errors and 0 session earnings.

**Comment by nexster** [comment]
Day 3 no Tfuel.  Now getting errors and warnings.

**Comment by Kuehn** [comment]
Hey everyone, sorry for the slow reply.  I will go through the run down, unfortunately the log error do appear to come back for me every once in while, however today I did get my first tFuel reward since trying to stake. Here is everything I did (unfortunately I don't think there is anything different that what you guys may have tried)

Thursday: Staked saw it was having errors, but left it for two days since I wasn't sure what was going on and thought it might take some time.

Saturday: 
Attempt #1: I decided to restart my node. This time when it loaded I was getting constant health checks failures in the recent activity and didn't let it run for that long as that seemed like an issue.

Attempt #2: I decided to delete my node database, delete my log file, and restart/sync my node database (I was reassured from reading other posts that deleting a node will not lose my current stake). At this point I was back at my original position of having the validate error, but no health check errors in the recent activity.

Sunday: I decided to delete my node database, delete my log file for a third time but this time I changed my performance tier to start to be Standard instead of Platinum (made sure I did it when I deleted my node as I didn't want the health check errors and that appeared to fix that.) This time I still got the errors in the log and came here, and once I reached out to telegram I was kind of embarrassed to find the errors were no longer there in the most recent part of the log. So The told me to likely delete my node database and resync if I have the issue again, but we didn't go into what it could have been since I wasn't producing it at the time. However I noticed later last night the errors do sometimes come back and go away, however today I got tfuel so i'm just going to monitor it for now and will update if I find an actual fix for it. 

Sorry this all I got right now hope it helps someone, but currently I'm not sure why I got tfuel today but nothing before, and nor do I know why the error message goes away and comes back. I did realize I don't exactly meet the minimum free space in my hard drive, so I might move it all to a different SSD that is 1 terabyte to see if that resolves it, if it appears not to give me tfuel anymore.

**Comment by sirbrokealot** [comment]
I have the same thought in mind @Kuehn . Maybe it needs the 1TB SSD storage and/or the PC might be too slow for it.
On Windows I tried to move the Guardian Node (GN) to a free 1 TB SSD.
I went to %appdata% (AppData\Roaming\Theta Guardian Node) and saved the ThetaGN folder without the db folder as backup.
I deleted all content in AppData\Roaming\Theta Guardian Node including the Theta Guardian Node folder and attempted a reinstall of GN.
This means I put the setup file on my fresh SSD and ran it.
On install I pointed GN to install the db in the very same fresh SSD.
I let it download.
When it turned towards the initial state of verifying close it and put your  ThetaGN back in the AppData\Roaming\Theta Guardian Node.
I hope that this will reinstall the GN in my fresh SSD without the trouble of restaking and getting rid of performance issues regarding to free disk space.
I will post here soon if it works.

**Comment by AquaWookie** [comment]
I see some workarounds to try to trick a failing node into working, but is there any official explanation or guidance on this matter?

**Comment by DavidGarry7654** [comment]
@AquaWookie Hi, what version of GN are you running on ?

**Comment by AquaWookie** [comment]
2.2.10

I've attempted to update, changed performance tiers etc. as well. Any suggestions?

**Comment by DavidGarry7654** [comment]
Okay. The only help I can render for you right now is to give you the theta network support group on Telegram. You can contact Theta Network Support on Telegram via the weblink https://t.me/thetanetworking. They'll be happy to resolve your issue. Cheers.

**Comment by AquaWookie** [comment]
According to what I see Theta has no official telegram. Can you show me where this is documented? I found about 4 scam 'official' telegrams, including people trying to pose as 'support/admins' offering bogus URLs that I won't post here that try to get you to unlock your wallet to 'fix the issue'.

I mean thanks if you're actually trying to help but the amount of scams in this space is gross, so many people will fall for them.

**Comment by nexster** [comment]
Day 4 no Tfuel....  last time I emailed theta customer support it took a week to get a response.   I figured it was fishy because they are busy with Mainnet 3.0.  No time for us peons.   But that’s ok as long as Launch goes smoothly.

**Comment by AquaWookie** [comment]
> Day 4 no Tfuel.... last time I emailed theta customer support it took a week to get a response. I figured it was fishy because they are busy with Mainnet 3.0. No time for us peons. But that’s ok as long as Launch goes smoothly.

Yeah that's basically what I'm hearing in the official Discord- it's a WIP and no one is coming to save us until after Main Net 3.0- that and to ignore all of these scammer cunts pushing Telegrams since they don't exist and are not official. 

(Looking at you DavidGarry)

**Comment by DavidGarry7654** [comment]
I just deleted the link too. I didn’t about it and I apologise

**Comment by sirbrokealot** [comment]
> I just deleted the link too. I didn’t about it and I apologise

DAVID IS A SCAMMER 

BE ADVISED

**Comment by the-quantum-rabbit** [comment]
> I found a lot of error message on log file. Is this normal?
> 
> [2021-03-11 18:10:38.112] [error] [2021-03-11 18:10:38] WARN [ledger] validateSourceAdvanced failed on 0xAE17b59b2587D01AFa10361b5045B14DB627B2E8: Result{code:100002, message:ValidateInputAdvanced: Got 4, expected 5. (acc.seq=4)}
> [2021-03-11 18:10:38.112] [info] [2021-03-11 18:10:38] WARN [ledger] validateSourceAdvanced failed on 0xAE17b59b2587D01AFa10361b5045B14DB627B2E8: Result{code:100002, message:ValidateInputAdvanced: Got 4, expected 5. (acc.seq=4)}

After much deleting database and snapshots and node restarts I finally fixed this issue in Ubuntu Linux by upgrading to the 2.2.0 theta process version from 2.1.0 by the process outlined in the manual.

curl -k --output bin/theta `curl -k 'https://mainnet-data.thetatoken.org/binary?os=linux&name=theta'`
curl -k --output bin/thetacli `curl -k 'https://mainnet-data.thetatoken.org/binary?os=linux&name=thetacli'`
chmod +x bin/theta
chmod +x bin/thetacli

and restarting the node.

Maybe just lucky ;-)

 As other people who have commented here the issue can happen with 2.2.0 and I do still see the messages, though less, and there is no loop with not getting sync'd. I finally get to a sync'd state OK.
 
So I conclude that the warning messages are normal but there is still some issue  if people have to fiddle like we have to get our nodes up and running. This could impact the robustness of the net.

THERE SHOULD BE A DOCUMENTED RECOVERY PROCEDURE HERE, MAINTAINING STAKED THETA.

**Comment by nexster** [comment]
Day 5.  No errors,  warnings persist.  No Tfuel.

**Comment by sirbrokealot** [comment]
Will try this now https://www.theta.tv/video/vid2sgb6k2fbnfjj9tk

**Comment by nexster** [comment]
Day 6.  No Tfuel.    Gonna give this a good 3-4 weeks before I do something.  Node is showing up as active so maybe it’s just not getting selected for blocks.

**Comment by nexster** [comment]
Day 7 Tfuel no Tfuel yet.

**Comment by Dahveed77** [comment]
Just dropping in to say that I have the exact same problem, with the same errors in my log.

I have been happily earning Tfuel for a couple months now, only once did I have a synching problem which I resolved by resetting, reinstalling etc...

Now I keep earning 0 Tfuel since a few days ago, which is disappointing.  Nothing I try seems to change anything, including changing tiers, deleting all files and reinstalling, restaking node, resetting peers, dancing naked while sacrificing children to c'thulu, etc.

Some sort of "official" answer would be reassuring.

**Comment by Garitty7612** [comment]
@Dahveed77 Hello Mate, Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink www.t.me/thetanetworking. They'll be happy to resolve your issue. Cheers.

**Comment by nexster** [comment]
Minimum payout is now 12 Tfuel.  I will start worrying after 14 days for my small stake.    Just updating daily to keep thread alive.

**Comment by Garitty7612** [comment]
@Dahveed77 Hello Mate, Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink www.t.me/thetanetworking. They'll be happy to resolve your issue. Cheers.

**Comment by nexster** [comment]
Theta does not have a telegram.

**Comment by phyx1u5** [comment]
> Just dropping in to say that I have the exact same problem, with the same errors in my log.
> 
> I have been happily earning Tfuel for a couple months now, only once did I have a synching problem which I resolved by resetting, reinstalling etc...
> 
> Now I keep earning 0 Tfuel since a few days ago, which is disappointing. Nothing I try seems to change anything, including changing tiers, deleting all files and reinstalling, restaking node, resetting peers, dancing naked while sacrificing children to c'thulu, etc.
> 
> Some sort of "official" answer would be reassuring.

I'm having the exact same problem. would be good to get an official response.
from what I can gather there is now a minimum threshold to payout so I'll keep waiting for a week or so and see if I get anything.

**Comment by nexster** [comment]
Day 8 no Tfuel.  My stake should make 12 every 10 days.  Crossing my fingers.

**Comment by Kuehn** [comment]
Update, after I earned Tfuel five days ago. The errors persist and I haven't received any since then, however I agree it's probably just the time to be patient as it appears that the rewards are less often but in bigger amounts as my reward last time was 12 tFuel. Good luck for everyone struggling with this issue as well. @sirbrokealot thanks for sharing the video that was very useful and I recommend everyone at least saving their keys off (as they demonstrate in the demo).  I agree this is an awesome project and hope they give more support and hopefully a bit after the mainnet 3.0 launch we will get further clarification for our issues.

**Comment by sirbrokealot** [comment]
@nexster thank you for showing us the "doing" nothing "don't change a running system" side of this issue! keep it on!
They don't have Telegram anymore. I REPEAT: THETA DOES NOT HAVE TELEGRAM.
But they have an official discord. @nexter have you tried the official discord @AquaWookie posted the channel link above.

@Dahveed77  I feel you. I also did change tiers, delete peers, delete database, reinstall several times with backup key insert (like they guy showed in the vid above).

Today I will finally be able to restake. This time I will carefully be downloading the most recent software. Stake via different browser. Install without crash or reboot. Choosing not the system drive as database storage. Then I will also dance naked while sacrificing children, pets and my left pinky to c'thulu.

I/we are running out of options so **I urge you all to write this issue to them in discord.**

This goes out to any Theta Guardian Node dev or representative: Should we just let it run buggy until you fix it via update or did we really mess up something?

**Comment by Kuehn** [comment]
Hi guys, I'm not sure this is going to be of any benefit as I'm a noob when it comes to all of this. But, have any of you that are failing to receive TFuel like @nexster checked their status of their node at https://guardianmonitor.io/ ? I didn't even realize it was a thing till yesterday. But if you go there and press control + F on your computer you can type in your node address and you should see it in the list of Guardian Nodes. On the columns to the right it should say Stable and Online (mine says stable and online and still haven't received tfuel for past 6 days but I don't have much so I think it's working). If yours does not I assume you won't get any tFuel no matter how long you wait (this is just speculation). Also there are other columns that state how much tfuel you have earned and how much you have lost. Maybe you guys know about this already but I came across it in a reddit post yesterday and wanted to make sure everyone who is new to this like me is aware of this site where they can monitor the status of their node.

**Comment by nexster** [comment]
Day 9.   No Tfuel.  My stake is 1140ish btw.   Crossing fingers as day 10 and 11 approaches.   

Guardian.Io says I have 10.5 Tfuel earned.   So I maybe ok.  Just impatient.

**Comment by phyx1u5** [comment]
Just to update all, after reinstalling my GN over and over and expecting regular rewards like before, I decide to leave my node running and now after 5 days of just letting it run I have finally received my first batch of 12 TFUEL. As another user stated, it seems there is now a payout limit of 12 TFUEL, so if you have not received any TFUEL yet just keep your node running and it will come eventually.
It would have been really good if this was made clear by the devs, as its taken a bit of fiddling about and headache trying to figure out what was wrong. Maybe if the devs could update the documentation that would be really helpful.

forgot to mention im running Linux CLI latest version

**Comment by learnwithallen** [comment]
I installed latest guardian node on Windows 10 using GUI program, got the same warning. The computer has 1TB hardware and literally is doing nothing but being a guardian node. I also tried deleting database and downgrading the performance tier all the way down to Standard.

So far a week after and 0 Tfuels earned. Love to hear how can fix this.

**Comment by Garitty7612** [comment]
@learnwithallen Hello Mate, Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink www.t.me/thetanetworking. They'll be happy to resolve your issue. Cheers.

**Comment by nexster** [comment]
Day 9 no Tfuel yet.

check guardian monitor.io to see if yours is showing as active.  Let it run a while and you can see if it’s accumulating any Tfuel.   

  Guardianmonitor.io shows I have 11.7 pending.   Will update if I get a payout.

**Comment by sirbrokealot** [comment]
@Garitty7612 IS A SCAMMER THETA DOES NOT HAVE TELEGRM ANYMORE ONLY DISCORD.
@nexster can not wait to hear good news from you.

**Comment by AquaWookie** [comment]
> @learnwithallen Hello Mate, Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink [www.t.me/thetanetworking](http://www.t.me/thetanetworking). They'll be happy to resolve your issue. Cheers.

THIS GUY IS A FUCKING SCAMMER, HES TRYING TO GET YOU TO LOSE YOUR THETA. I HOPE HE DIES OF AIDS OF THE EYES.

**Comment by AquaWookie** [comment]
That said, in leaving my node running- I received a payout of 12 Theta Fuel in a bulk.

They must have changed the way the network processes, not told anyone, caused a bunch of errors on the client because of it- but it still functions.

**Comment by nexster** [comment]
Day 10 no tfuel...

**Comment by nexster** [comment]
Day 11 no Tfuel.   They the really need to have a way to show if you have any pending.   Super frustrating.

**Comment by GitHinse** [comment]
Hold the line! As long as you see no error message on your node, you ought to be rewarded.

This guy helped me to let it go and stop watching my node everyday

https://www.youtube.com/watch?v=n4yzOLsoeeg

Also you may check the status of your GN at guardianmonitor.io, just ctrl+f your node ID to get an idea on how it's doing

**Comment by nexster** [comment]
Just aggravating to see an free edge node make more everyday than a stake that is $10k +.

**Comment by rrln** [comment]
> 
> 
> I found a lot of error message on log file. Is this normal?
> 
> [2021-03-11 18:10:38.112] [error] [2021-03-11 18:10:38] WARN [ledger] validateSourceAdvanced failed on 0xAE17b59b2587D01AFa10361b5045B14DB627B2E8: Result{code:100002, message:ValidateInputAdvanced: Got 4, expected 5. (acc.seq=4)}
> [2021-03-11 18:10:38.112] [info] [2021-03-11 18:10:38] WARN [ledger] validateSourceAdvanced failed on 0xAE17b59b2587D01AFa10361b5045B14DB627B2E8: Result{code:100002, message:ValidateInputAdvanced: Got 4, expected 5. (acc.seq=4)}

Hi, I have not read all posts here but like to shed some light over this.
The warning and error message about ValidateInputAdvanced, can be ignored.
I have them in my log files and I have no problem.
I found a messeage from a devloper at theta labs in a thread here at github where he confirmed this. I forget where, sorry for that.

The problem I had was due to the Mainnet 2.2.0 upgrade. I had tor reinstall booth Windows and Linux clients to get it to work again (v2.2.10). The message about ValidateInputAdvanced is unrelated to this.

As many already has stated, check your network connectivity at https://guardianmonitor.io/.
Status should be ONLINE/STABLE and 30DMB (30 Day Missed Blocks) should be as low as possible.

For the expectation of how often you get reward.
The reward is payed out in 12 TFULE shunks.
The reward is currently 4%.
If you have staked 1000 THETA, you have currently staked $12774.
Annual reward is 0.04*12774 = $511
That is 511/12 = 42.6 payouts of $12 rewards in a year.
The payout interval is 364/46,2 = 8.57 days in average.
The payout intervall is randomized as well so it can be longer/shorter than that.

**Comment by nexster** [comment]
I have 2355 missed blocks which is more than some that are flatlined.    So I am gonna say My node has problems.  I guess I will just stake to guardian pool.  So much for supporting decentralization.

**Comment by learnwithallen** [comment]
Just my observation how the reward system is badly set up, staking thousands' of dollar in the network earns less than simply running an edge node with no staking. Running a guardian node for 10 days and no fuel drop is just bad.

**Comment by rrln** [comment]
> 
> 
> Just my observation how the reward system is badly set up, staking thousands' of dollar in the network earns less than simply running an edge node with no staking. Running a guardian node for 10 days and no fuel drop is just bad.

You migh just be lucky with your edge node, I receive very few Edge Cache jobs.

**Comment by nexster** [comment]
Looks like my missed block count is going down slowly.  Will keep an eye on it before unstaking.

**Comment by GitHinse** [comment]
Those are measured for a 30 day period. Give it time and it should trend toward 0. Those you missed might simply have happened while you were syncing originally or something like that... at least this is the comprehension I have of this so far... which is definitely far from an expert opinion :) we'll see in a few weeks how wrong I was

**Comment by nexster** [comment]
Feeling better,  my 1 day and 7 day blocks signed are 100%.       30 day blocks signed rising.

**Comment by nexster** [comment]
Day 12 no Tfuel.

**Comment by nexster** [comment]
Now getting error... skip vote...

**Comment by nexster** [comment]
Giving up and staking to gpool on day 16.

**Comment by nexster** [comment]
Day 13 no Tfuel.

**Comment by GitHinse** [comment]
Update for you  @nexster, I got my 2nd 12pack of tFuel on day 12 with the minimum 1000 tokens staked on my node!

**Comment by nexster** [comment]
I still have none since the update.   I unstaked.  Will re-format my hard drive and retry.  Something must have got corrupted when my power went out unexpectedly.

**Comment by PilotManForever** [comment]
> > I emailed the Theta support team. Will keep everyone updated here.
> 
> Hi Everyone,
> 
> I still have not heard back from the support team but I am starting to see TFuel earnings on my guardian node.
> 
> I suspect the log error:
> 
> "WARN [ledger] validateSourceAdvanced failed on 0x90a5C68EB3A4391fb48f9e7bd7B2d39Fb32601CD: Result{code:100002, message:ValidateInputAdvanced: Got 60, expected 61. (acc.seq=60)}"... Is unrelated to the tfuel sessions earning issue and may be a natural part of the guardian node and not a "bug".

Please Keep me in the loop on this.  Same issue with a new setup.  Is there a way to follow you on here?   Hmmmmm.

**Comment by nexster** [comment]
Got it up and running again with a brand new 1Tb SSD and getting same skip vote errors etc.   Not a good omen for project if they can get nodes to work.   Will wait 10 days for a Tfuel drop.  And update then.

**Comment by Mlemus59** [comment]
Have the same issues you had.  Did you resolve your issue?

**Comment by nexster** [comment]
I solved it by staking to gpool.  Free and safe .

**Comment by Mlemus59** [comment]
Thanks
Marty L. Lemus 

    On Sunday, May 23, 2021, 12:02:12 AM EDT, nexster ***@***.***> wrote:  
 
 


I solved it by staking to gpool. Free and safe .
